### ISSUE TITLE
Not rendering some symbols in Google Chrome (Windows 8)

### ISSUE THREAD

**Issue by Semigradsky** [primer/markdown#49]
Some symbols not correctly rendering (&#x2B06; for example).

In Chrome:
![image](https://cloud.githubusercontent.com/assets/1198848/7680404/df72f722-fd6e-11e4-82a3-46b459997c71.png)

In Firefox and IE all good:
![image](https://cloud.githubusercontent.com/assets/1198848/7680441/46bc5da6-fd6f-11e4-8fe6-755a79ee0148.png)

Symbols correctly rendering if styles will be changed:
from
```css
.markdown-body {
  font-family: "Helvetica Neue", Helvetica, "Segoe UI", Arial, freesans, sans-serif;
}
```
to
```css
.markdown-body {
  font-family: "Helvetica Neue", Helvetica, "Segoe UI", Arial, freesans, sans-serif; "Segoe UI Symbol";
}
```
